import httpx
from dataclasses import dataclass, fields
from typing import Any, Optional, Final
from datetime import datetime
from .enums import (
    EightyPlusRating, Modularity, Series, Size,
    Tier, Wattage, WattageData, WattageMinMax,
    Topology, PrimaryConversion, SecondaryRectifier,
    SecondaryRegulation
)


@dataclass
class Item:
    """
    Note: Some values are missing that were deemed useless in 99.9% of cases, such as hashes and pocketbase collection stuff
    :param full_name: A string generated by the API to serve as the PSU name. It seems to consist of brand + series + sub series 1 + sub series 2 + year string.
    """
    efficiency: EightyPlusRating
    notes: str
    atx_version: str
    bearing: str
    brand: str
    created: str
    fet_brand: str
    full_name: str
    id: str
    input_voltage: str
    modularity: Modularity
    ocp: str
    odm: str
    otp: bool
    pfc: str
    platform_code: str
    platform_code_notes: str
    series: Series
    size: Size
    tier: Tier
    topology: Topology
    updated: str
    wattage_data: WattageData
    year_dt: datetime | None
    year_string: str

    @classmethod
    def from_raw_dict(cls, item_raw: dict[str, Any]) -> "Item":
        eightyplus = EightyPlusRating.from_str(item_raw.get("80_plus_efficiency", "NONE"))
        notes = str(item_raw.get("Notes", ""))

        wattages: list[Wattage] = []
        for index in range(10):
            wtg = item_raw.get(f"wattage_{index}", None)
            wtg_aff_lnk = item_raw.get(f"wattage_{index}_affiliate_link", None)
            if wtg:
                wattages.append(Wattage(
                    w=int(wtg),
                    psu_tierlist_affiliate_link=str(wtg_aff_lnk) if wtg_aff_lnk else None
                ))

        wattage_data = WattageData(
            wattages=wattages,
            min_max=WattageMinMax(
                min=item_raw.get("wattmin", None),
                max=item_raw.get("wattmax", None)
            )
        )

        year: str | None = str(item_raw.get("year", None)) if item_raw.get("year", None) else None
        year_dt: datetime | None = datetime.fromisoformat(year.replace("Z", "+00:00")) if year else None

        topology = Topology(
            primary_conversion=PrimaryConversion.from_str(item_raw.get("topology_primary_conversion", "OTHER_OR_UNKNOWN")),
            secondary_rectifier=SecondaryRectifier.from_str(item_raw.get("topology_secondary_rectifier", "OTHER_OR_UNKNOWN")),
            secondary_regulation=SecondaryRegulation.from_str(item_raw.get("topology_secondary_regulation", "OTHER_OR_UNKNOWN"))
        )

        tier = Tier.from_str(
            name=str(item_raw.get("tier", "UNKNOWN")),
            modifier=str(item_raw.get("tier_mod", ""))
        )

        series = Series(
            series=str(item_raw.get("series", None)),
            sub_series_1=item_raw.get("sub_series_1", None),
            sub_series_2=item_raw.get("sub_series_2", None)
        )

        size = Size.from_str(str(item_raw.get("size", "UNKNOWN")))

        modularity = Modularity.from_str(str(item_raw.get("modularity", "UNKNOWN")))

        return Item(
            efficiency=eightyplus,
            notes=notes,
            wattage_data=wattage_data,
            year_dt=year_dt,
            topology=topology,
            tier=tier,
            series=series,
            size=size,
            modularity=modularity,
            **{k: v for k, v in item_raw.items() if k in _ITEM_FIELDS}
        )


# this is down here because item needs to be defined first
_ITEM_FIELDS: Final[set[str]] = {f.name for f in fields(Item)}


@dataclass
class Response:
    items: list["Item"]
    perPage: int
    totalItems: int
    totalPages: int

    @classmethod
    def from_raw_dict(cls, response: dict[str, Any]) -> Optional["Response"]:
        items_raw: list[dict[str, Any]] | None = response.get("items", None)

        if not items_raw:
            return None

        items: list[Item] = []

        for item_raw in items_raw:
            items.append(Item.from_raw_dict(item_raw))

        return Response(
            items=items,
            perPage=int(response.get("perPage", 0)),
            totalItems=int(response.get("totalItems", 0)),
            totalPages=int(response.get("totalPages", 0))
        )


class API:
    def __init__(self) -> None:
        self.api_url: Final[str] = "https://pb.psutierlist.org/api/collections/psu_tier_list/records?page={page}&perPage=500"

    def get(self, client: httpx.Client, page: int) -> httpx.Response:
        """
        Retrieves a single page of PSUs and returns a httpx.Response (not to be confused with the Response dataclass)

        Requires an httpx.Client to be passed in, in addition to the page to retrieve.
        """

        response = client.get(url=self.api_url.format(page=page))

        if response.status_code == 200:
            return response
        else:
            return response.raise_for_status()

    async def get_async(self, client: httpx.AsyncClient, page: int) -> httpx.Response:
        """
        Async version of get(). Retrieves a single page of PSUs and returns a httpx.Response.

        Requires an httpx.AsyncClient.
        """

        response = await client.get(url=self.api_url.format(page=page))

        if response.status_code == 200:
            return response
        else:
            return response.raise_for_status()


def get_pages() -> Response | None:
    """
    Retrieves all pages of PSUs, combines the items lists, and returns a single Response object.
    """

    api = API()
    items_combined: list[dict[str, Any]] = []

    with httpx.Client(timeout=10) as client:
        # Retrieve first page to get the first page + page count
        response = api.get(client=client, page=1)

        if not response:
            return None

        json_response: dict[str, Any] = response.json()

        # Gather all necessary fields
        perPage = int(json_response.get("perPage", 0))
        totalItems = int(json_response.get("totalItems", 0))
        totalPages = int(json_response.get("totalPages", 0))
        items_combined.extend(json_response.get("items", []))

        # Retrieve remaining pages:
        # Start at 2 since we already have page 1
        # Add 1 to totalPages since range is exclusive on the end (why? idk i dont think it makes any sense)
        for page in range(2, totalPages + 1):
            response = api.get(client=client, page=page)

            if not response:
                return None

            json_response = response.json()
            items_combined.extend(json_response.get("items", []))

    # Return the final Response object using the .from_raw_dict() method + the combined dict we are creating
    return Response.from_raw_dict({
        "items": items_combined,
        "perPage": perPage,
        "totalItems": totalItems,
        "totalPages": totalPages
    })


async def get_pages_async() -> Response | None:
    """
    Retrieves all pages of PSUs asynchronously, combines the items lists, and returns a single Response object.
    """

    api = API()
    items_combined: list[dict[str, Any]] = []

    async with httpx.AsyncClient(timeout=10) as client:
        # Retrieve first page to get the first page + page count
        response = await api.get_async(client=client, page=1)

        if not response:
            return None

        json_response: dict[str, Any] = response.json()

        # Gather all necessary fields
        perPage = int(json_response.get("perPage", 0))
        totalItems = int(json_response.get("totalItems", 0))
        totalPages = int(json_response.get("totalPages", 0))
        items_combined.extend(json_response.get("items", []))

        # Retrieve remaining pages:
        # Start at 2 since we already have page 1
        # Add 1 to totalPages since range is exclusive on the end (why? idk i dont think it makes any sense)
        for page in range(2, totalPages + 1):
            response = await api.get_async(client=client, page=page)

            if not response:
                return None

            json_response = response.json()
            items_combined.extend(json_response.get("items", []))

    # Return the final Response object using the .from_raw_dict() method + the combined dict we are creating
    return Response.from_raw_dict({
        "items": items_combined,
        "perPage": perPage,
        "totalItems": totalItems,
        "totalPages": totalPages
    })
