[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "psutierlist-api-wrapper"
version = "v1.0.1"
description = "API Wrapper"
readme = "README.md"
requires-python = ">=3.11"
license = "AGPL-3.0-only"
license-files = ["LICEN[CS]E*"]
authors = [{name = "PowerPCFan", email = "charlie@powerpcfan.xyz"}]
maintainers = [{name = "PowerPCFan", email = "charlie@powerpcfan.xyz"}]
dependencies = [
    "httpx >= 0.28.1",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Repository = "https://github.com/PowerPCFan/psutierlist-api-wrapper"
Issues = "https://github.com/PowerPCFan/psutierlist-api-wrapper/issues"
